--JDBC(Java DataBase Connectivity)
CREATE SEQUENCE MEMBER_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100;

CREATE TABLE TBL_MEMBER(
	NUM NUMBER,
	ID VARCHAR2(200),
	PW VARCHAR2(200),
	NAME VARCHAR2(200),
	AGE NUMBER,
	CONSTRAINT MEMBER_PK PRIMARY KEY(NUM) 
);

SELECT * FROM TBL_MEMBER;